/**
 * Canonical icon name → Lucide glyph map (doc 13 D-3).
 *
 * The docs reference icons by *canonical semantic name* (`home`, `package`,
 * `scale`, …). This map is the SSOT for which names exist; the underlying
 * library (Lucide) is swappable without touching a single call site or doc,
 * because call sites only ever pass a canonical name to `FxIcon`.
 *
 * Names are seeded from every icon referenced across docs 02/06/08
 * (`tests/icon-map.spec.ts` holds that seed list verbatim and fails the build
 * if any seeded name is missing here). A missing name is a build error, never a
 * silent fallback.
 */
import {
  Activity,
  AlertCircle,
  AlertTriangle,
  ArrowLeft,
  ArrowUp,
  AtSign,
  BarChart3,
  Bell,
  Calendar,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronRight,
  Clock,
  Copy,
  CreditCard,
  Download,
  Eye,
  EyeOff,
  ExternalLink,
  File,
  Filter,
  GripVertical,
  Heart,
  History,
  Home,
  Image,
  Info,
  Landmark,
  LayoutGrid,
  Lock,
  Maximize2,
  Menu,
  MessageSquare,
  Minus,
  MoreHorizontal,
  Music,
  Package,
  Paperclip,
  Pause,
  Pencil,
  Play,
  Plus,
  RefreshCw,
  Reply,
  RotateCcw,
  Scale,
  Search,
  Send,
  Settings,
  ShieldCheck,
  SlidersHorizontal,
  Sparkles,
  Square,
  Star,
  Tag,
  Trash2,
  TrendingDown,
  TrendingUp,
  Upload,
  Users,
  Video,
  Wallet,
  WifiOff,
  X,
  type LucideIcon,
} from 'lucide-react';

export const ICON_MAP = {
  activity: Activity,
  'at-sign': AtSign,
  back: ArrowLeft,
  bank: Landmark,
  bell: Bell,
  calendar: Calendar,
  card: CreditCard,
  chart: BarChart3,
  chat: MessageSquare,
  check: Check,
  chevron: ChevronRight,
  'chevron-down': ChevronDown,
  clock: Clock,
  close: X,
  copy: Copy,
  download: Download,
  edit: Pencil,
  error: AlertCircle,
  eye: Eye,
  'eye-off': EyeOff,
  'external-link': ExternalLink,
  file: File,
  filter: Filter,
  grid: LayoutGrid,
  grip: GripVertical,
  heart: Heart,
  history: History,
  home: Home,
  image: Image,
  info: Info,
  inherit: ArrowUp,
  lock: Lock,
  maximize: Maximize2,
  menu: Menu,
  minus: Minus,
  more: MoreHorizontal,
  music: Music,
  package: Package,
  paperclip: Paperclip,
  pause: Pause,
  play: Play,
  plus: Plus,
  refresh: RefreshCw,
  reply: Reply,
  'rotate-ccw': RotateCcw,
  scale: Scale,
  search: Search,
  send: Send,
  settings: Settings,
  'shield-check': ShieldCheck,
  sliders: SlidersHorizontal,
  sparkle: Sparkles,
  star: Star,
  stop: Square,
  success: CheckCircle2,
  tag: Tag,
  trash: Trash2,
  'trending-down': TrendingDown,
  'trending-up': TrendingUp,
  upload: Upload,
  users: Users,
  video: Video,
  wallet: Wallet,
  'wifi-off': WifiOff,
  warning: AlertTriangle,
} satisfies Record<string, LucideIcon>;

/** Every canonical icon name available to `FxIcon`. */
export type IconName = keyof typeof ICON_MAP;

/** Runtime list of canonical names (for pickers, tests, docs). */
export const ICON_NAMES = Object.keys(ICON_MAP) as IconName[];
