/**
 * Drift-lock for the distributable CSS artifacts (FDS-2, doc 19) — dist/*.css is
 * generated by scripts/build-css.ts from the SAME canonical emitters this package
 * exports; this spec pins that equivalence (mirror of the flexa-token-ids.json
 * asset gate). Run `pnpm build` first — like the WP asset gate, artifacts are
 * build outputs, not committed files.
 */
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { describe, expect, it } from 'vitest';
import { FDS_VERSION, defaultTheme, emitBaseTypography, emitTheme } from '../src/index.js';

const dist = join(dirname(fileURLToPath(import.meta.url)), '..', 'dist');

/** Strip the one-line banner comment; the rest must be emitter bytes verbatim. */
function body(file: string): { banner: string; css: string } {
  const raw = readFileSync(join(dist, file), 'utf8');
  const nl = raw.indexOf('\n');
  return { banner: raw.slice(0, nl), css: raw.slice(nl + 1) };
}

describe('dist CSS artifacts stay in sync with the canonical emitters (FDS-2)', () => {
  it('theme.css = emitTheme(defaultTheme()), versioned banner', () => {
    const { banner, css } = body('theme.css');
    expect(banner.startsWith(`/*! Flexa Design System v${FDS_VERSION}`)).toBe(true);
    expect(css).toBe(emitTheme(defaultTheme()) + '\n');
  });

  it('base-typography.css = emitBaseTypography(), versioned banner', () => {
    const { banner, css } = body('base-typography.css');
    expect(banner.startsWith(`/*! Flexa Design System v${FDS_VERSION}`)).toBe(true);
    expect(css).toBe(emitBaseTypography() + '\n');
  });
});
