/**
 * Drift-lock for the distributable CSS artifact (U12) — `dist/styles.css` is
 * generated by `scripts/build-css.ts` from the SAME per-component stylesheets and
 * the SAME order as `src/styles.css` (the single source of truth). This spec pins
 * that equivalence, mirroring the FDS-2 `artifacts.spec.ts`.
 *
 * Like the FDS artifact gate, `dist/` is a build output (gitignored) — run
 * `pnpm --filter flexa-ui-kit build` first.
 */
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { describe, expect, it } from 'vitest';
import { UI_VERSION } from '../src/index.js';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');

/** Re-derive styles.css exactly as scripts/build-css.ts does. */
function expectedStyles(): { banner: string; css: string } {
  const aggregator = readFileSync(join(root, 'src/styles.css'), 'utf8');
  const files = [...aggregator.matchAll(/@import\s+'(\.\/[^']+)'/g)].map((m) => join('src', m[1]!));
  const banner = `/*! flexa-ui-kit v${UI_VERSION} — styles.css | MIT | https://github.com/chidang/flexa-builder */`;
  const css = files.map((f) => readFileSync(join(root, f), 'utf8')).join('\n') + '\n';
  return { banner, css };
}

describe('dist CSS artifact stays in sync with the component stylesheets (U12)', () => {
  it('styles.css = versioned banner + every component stylesheet, src order', () => {
    const raw = readFileSync(join(root, 'dist/styles.css'), 'utf8');
    const nl = raw.indexOf('\n');
    const banner = raw.slice(0, nl);
    const css = raw.slice(nl + 1);

    const expected = expectedStyles();
    expect(banner).toBe(expected.banner);
    expect(css).toBe(expected.css);
  });
});
